name: Deploy PostgreSQL to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar la clave SSH para conectarse a la instancia EC2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Paso 2: Desplegar el contenedor PostgreSQL en la instancia EC2
      - name: Deploy PostgreSQL container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Detener y eliminar cualquier contenedor existente con el mismo nombre
            docker stop postgresql-dev || true
            docker rm postgresql-dev || true

            # Ejecutar el contenedor PostgreSQL
            docker run -d \
              --name postgresql-dev \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -p 5432:5432 \
              postgres:15
          EOF